/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4d5f80",
        "secondary-fixed": "#dbe1ff",
        "on-error": "#ffffff",
        primary: "#000718",
        "on-tertiary-container": "#7187b4",
        "secondary-container": "#316bf3",
        "on-primary-fixed": "#061b39",
        "on-tertiary-fixed-variant": "#304670",
        "inverse-primary": "#b5c7ed",
        background: "#f7f9fc",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#b0c7f8",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#354767",
        outline: "#75777e",
        "surface-variant": "#e0e3e6",
        "surface-container": "#eceef1",
        "surface-dim": "#d8dadd",
        surface: "#f7f9fc",
        "on-secondary-container": "#fefcff",
        "on-tertiary-fixed": "#001a40",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#b4c5ff",
        secondary: "#0051d5",
        "primary-fixed-dim": "#b5c7ed",
        "tertiary-container": "#011e46",
        tertiary: "#000618",
        "primary-container": "#0b1f3d",
        error: "#ba1a1a",
        "surface-container-low": "#f2f4f7",
        "inverse-on-surface": "#eff1f4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d7e2ff",
        "on-primary-container": "#7687ab",
        "on-background": "#191c1e",
        "on-surface-variant": "#44474e",
        "surface-container-highest": "#e0e3e6",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "on-secondary-fixed": "#00174b",
        "outline-variant": "#c5c6ce",
        "on-error-container": "#93000a",
        "primary-fixed": "#d7e3ff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fc",
        "inverse-surface": "#2d3133",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        margin: "2rem",
        "space-xs": "0.5rem",
        "space-2xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        body: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-sm-medium": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md-medium": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md-medium": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      // Animasi microenvironment: hanya transform + opacity (tidak menyentuh
      // layout), jadi tetap murah di GPU. Prefix "sp" = SimPres.
      keyframes: {
        "sp-rise": {
          "0%": { opacity: "0", transform: "translate3d(0, 12px, 0)" },
          "100%": { opacity: "1", transform: "translate3d(0, 0, 0)" },
        },
        "sp-slide": {
          "0%": { opacity: "0", transform: "translate3d(16px, 0, 0)" },
          "100%": { opacity: "1", transform: "translate3d(0, 0, 0)" },
        },
        "sp-drift-x": {
          "0%": { transform: "translate3d(0, 0, 0)" },
          "100%": { transform: "translate3d(12px, -8px, 0)" },
        },
        "sp-glow": {
          "0%, 100%": { opacity: "0.45" },
          "50%": { opacity: "1" },
        },
        "sp-sweep": {
          "0%": { transform: "translateX(-120%)" },
          "100%": { transform: "translateX(320%)" },
        },
        "sp-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        "sp-fade": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "sp-scan": {
          "0%": { transform: "translate3d(-20%, 0, 0)" },
          "100%": { transform: "translate3d(120%, 0, 0)" },
        },
      },
      animation: {
        "sp-rise": "sp-rise 0.62s cubic-bezier(0.22, 1, 0.36, 1) both",
        "sp-slide": "sp-slide 0.72s cubic-bezier(0.22, 1, 0.36, 1) both",
        "sp-drift-x": "sp-drift-x 32s ease-in-out infinite alternate",
        "sp-glow": "sp-glow 5.5s ease-in-out infinite",
        "sp-sweep": "sp-sweep 1.8s cubic-bezier(0.4, 0, 0.2, 1) infinite",
        "sp-dot": "sp-dot 2.6s ease-in-out infinite",
        "sp-fade": "sp-fade 0.5s cubic-bezier(0.22, 1, 0.36, 1) both",
        "sp-scan": "sp-scan 34s linear infinite",
      },
    },
  },
  plugins: [],
}
